name: babydiary_pub
description: BabyDiary
version: 1.0.0+1

environment:
  sdk: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: any
  settings_ui: ^2.0.2
  flutter_slidable: ^3.1.0
  sqflite: any
  path: any
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.5
  equatable: ^2.0.0
  fluttertoast: ^8.2.6
  group_button: ^5.3.4
  flex_color_scheme: ^7.3.1
  easy_localization: ^3.0.7
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  flutter_carousel_widget: ^2.2.0
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png